# helm/http-echo/values.yaml
# Default values for http-echo chart
app:
  name: "http-echo"
  response: "hello"
  port: 5678

replicaCount: 2

image:
  repository: hashicorp/http-echo
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

# Health check configuration
healthCheck:
  enabled: true
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 5
  successThreshold: 1
  failureThreshold: 3

# Pod disruption budget
podDisruptionBudget:
  enabled: true
  minAvailable: 1

# Labels and annotations
labels:
  component: http-echo
  
annotations: {}

# Security context
securityContext:
  runAsNonRoot: true
  runAsUser: 1000
  fsGroup: 2000

# Node selector, tolerations and affinity
nodeSelector: {}
tolerations: []
affinity: {}