# kind-config.yaml
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 80
        hostPort: 8080   # change from 80
        protocol: TCP
      - containerPort: 443
        hostPort: 8443   # change from 443
        protocol: TCP
