{{- if (default false .Values.podDisruptionBudget.enabled) }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ .Values.app.name }}-pdb
  labels:
    {{- include "http-echo.labels" . | nindent 4 }}
spec:
  minAvailable: {{ default 1 .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "http-echo.selectorLabels" . | nindent 6 }}
{{- end }}
